<?php
namespace Caridea\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-16 at 13:07:12.
 */
class BuilderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Caridea\Filter\Builder::field
     * @covers Caridea\Filter\Builder::always
     * @covers Caridea\Filter\Builder::build
     * @covers Caridea\Filter\Builder::__construct
     */
    public function testBuilder()
    {
        $registry = new Registry();
        $builder = new Builder($registry);
        $c1 = $builder->field('name');
        $this->assertInstanceOf(Chain::class, $c1);
        $this->assertFalse($c1->isRequired());
        $c1->then('trim')->then('titlecase');
        $c2 = $builder->always('age');
        $this->assertInstanceOf(Chain::class, $c2);
        $this->assertTrue($c2->isRequired());
        $c2->then('string')->then('default', 0);
        $c3 = $builder->field('sex');
        $this->assertInstanceOf(Chain::class, $c3);
        $filter = $builder->build();
        $this->assertInstanceOf(Filter::class, $filter);
        $this->assertAttributeCount(2, 'chains', $filter);
    }
}
