<?php
namespace Caridea\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-09-16 at 16:38:49.
 */
class OtherwiseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers Caridea\Filter\Otherwise::__construct
     * @covers Caridea\Filter\Otherwise::__invoke
     */
    public function test__invoke()
    {
        $registry = new Registry();
        $chain = new Chain($registry);
        $chain->then('trim');
        $otherwise = new Otherwise($chain, ['name' => 1, 'age' => 2]);
        $input = ['name' => 'Me', 'age' => 900, 'foo' => ' bar '];
        $this->assertEquals(['foo' => 'bar'], $otherwise($input));
    }
}
